# Codecov configuration for {{ModuleName}}
# Documentation: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - {{ModuleName}}/
    carryforward: true

ignore:
  - "tests/**/*"
  - "*.tests.ps1"
  - "build.ps1"
  - "build.psake.ps1"
  - "build.depend.psd1"
